X(read, 3, long, "unsigned int fd, char __user *buf, size_t count")
X(write, 3, long, "unsigned int fd, const char __user *buf, size_t count")
X(open, 3, long, "const char __user *filename, int flags, umode_t mode")
X(close, 1, long, "unsigned int fd")
X(stat, 2, long, "const char __user *filename, struct stat __user *statbuf")
X(fstat, 2, long, "unsigned int fd, struct stat __user *statbuf")
X(lstat, 2, long, "const char __user *filename, struct stat __user *statbuf")
X(poll, 3, long, "struct pollfd __user *ufds, unsigned int nfds, int timeout")
X(lseek, 3, long, "unsigned int fd, off_t offset, unsigned int whence")
X(mmap, 6, "?", "?")
X(mprotect, 3, long, "unsigned long start, size_t len, unsigned long prot")
X(munmap, 2, long, "unsigned long addr, size_t len")
X(brk, 1, long, "unsigned long brk")
X(rt_sigaction, 4, long, "int, const struct sigaction __user *, struct sigaction __user *, size_t")
X(rt_sigprocmask, 4, long, "int how, sigset_t __user *set, sigset_t __user *oset, size_t sigsetsize")
X(rt_sigreturn, 0, "?", "?")
X(ioctl, 3, long, "unsigned int fd, unsigned int cmd, unsigned long arg")
X(pread64, 4, long, "unsigned int fd, char __user *buf, size_t count, loff_t pos")
X(pwrite64, 4, long, "unsigned int fd, const char __user *buf, size_t count, loff_t pos")
X(readv, 3, long, "unsigned long fd, const struct iovec __user *vec, unsigned long vlen")
X(writev, 3, long, "unsigned long fd, const struct iovec __user *vec, unsigned long vlen")
X(access, 2, long, "const char __user *filename, int mode")
X(pipe, 1, long, "int __user *fildes")
X(select, 5, long, "int n, fd_set __user *inp, fd_set __user *outp, fd_set __user *exp, struct timeval __user *tvp")
X(sched_yield, 0, long, "")
X(mremap, 5, long, "unsigned long addr, unsigned long old_len, unsigned long new_len, unsigned long flags, unsigned long new_addr")
X(msync, 3, long, "unsigned long start, size_t len, int flags")
X(mincore, 3, long, "unsigned long start, size_t len, unsigned char __user * vec")
X(madvise, 3, long, "unsigned long start, size_t len, int behavior")
X(shmget, 3, long, "key_t key, size_t size, int flag")
X(shmat, 3, long, "int shmid, char __user *shmaddr, int shmflg")
X(shmctl, 3, long, "int shmid, int cmd, struct shmid_ds __user *buf")
X(dup, 1, long, "unsigned int fildes")
X(dup2, 2, long, "unsigned int oldfd, unsigned int newfd")
X(pause, 0, long, "")
X(nanosleep, 2, long, "struct timespec __user *rqtp, struct timespec __user *rmtp")
X(getitimer, 2, long, "int which, struct itimerval __user *value")
X(alarm, 1, long, "unsigned int seconds")
X(setitimer, 3, long, "int which, struct itimerval __user *value, struct itimerval __user *ovalue")
X(getpid, 0, long, "")
X(sendfile, 4, long, "int out_fd, int in_fd, loff_t __user *offset, size_t count")
X(socket, 3, long, "int, int, int")
X(connect, 3, long, "int, struct sockaddr __user *, int")
X(accept, 3, long, "int, struct sockaddr __user *, int __user *")
X(sendto, 6, long, "int, void __user *, size_t, unsigned, struct sockaddr __user *, int")
X(recvfrom, 6, long, "int, void __user *, size_t, unsigned, struct sockaddr __user *, int __user *")
X(sendmsg, 3, long, "int fd, struct user_msghdr __user *msg, unsigned flags")
X(recvmsg, 3, long, "int fd, struct user_msghdr __user *msg, unsigned flags")
X(shutdown, 2, long, "int, int")
X(bind, 3, long, "int, struct sockaddr __user *, int")
X(listen, 2, long, "int, int")
X(getsockname, 3, long, "int, struct sockaddr __user *, int __user *")
X(getpeername, 3, long, "int, struct sockaddr __user *, int __user *")
X(socketpair, 4, long, "int, int, int, int __user *")
X(setsockopt, 5, long, "int fd, int level, int optname, char __user *optval, int optlen")
X(getsockopt, 5, long, "int fd, int level, int optname, char __user *optval, int __user *optlen")
X(clone, 5, "?", "?")
X(fork, 0, long, "")
X(vfork, 0, long, "")
X(execve, 3, long, "const char __user *filename, const char __user *const __user *argv, const char __user *const __user *envp")
X(exit, 1, long, "int error_code")
X(wait4, 4, long, "pid_t pid, int __user *stat_addr, int options, struct rusage __user *ru")
X(kill, 2, long, "pid_t pid, int sig")
X(uname, 1, long, "struct new_utsname __user *name")
X(semget, 3, long, "key_t key, int nsems, int semflg")
X(semop, 3, long, "int semid, struct sembuf __user *sops, unsigned nsops")
X(semctl, 4, long, "int semid, int semnum, int cmd, unsigned long arg")
X(shmdt, 1, long, "char __user *shmaddr")
X(msgget, 2, long, "key_t key, int msgflg")
X(msgsnd, 4, long, "int msqid, struct msgbuf __user *msgp, size_t msgsz, int msgflg")
X(msgrcv, 5, long, "int msqid, struct msgbuf __user *msgp, size_t msgsz, long msgtyp, int msgflg")
X(msgctl, 3, long, "int msqid, int cmd, struct msqid_ds __user *buf")
X(fcntl, 3, long, "unsigned int fd, unsigned int cmd, unsigned long arg")
X(flock, 2, long, "unsigned int fd, unsigned int cmd")
X(fsync, 1, long, "unsigned int fd")
X(fdatasync, 1, long, "unsigned int fd")
X(truncate, 2, long, "const char __user *path, long length")
X(ftruncate, 2, long, "unsigned int fd, unsigned long length")
X(getdents, 3, long, "unsigned int fd, struct linux_dirent __user *dirent, unsigned int count")
X(getcwd, 2, long, "char __user *buf, unsigned long size")
X(chdir, 1, long, "const char __user *filename")
X(fchdir, 1, long, "unsigned int fd")
X(rename, 2, long, "const char __user *oldname, const char __user *newname")
X(mkdir, 2, long, "const char __user *pathname, umode_t mode")
X(rmdir, 1, long, "const char __user *pathname")
X(creat, 2, long, "const char __user *pathname, umode_t mode")
X(link, 2, long, "const char __user *oldname, const char __user *newname")
X(unlink, 1, long, "const char __user *pathname")
X(symlink, 2, long, "const char __user *old, const char __user *new")
X(readlink, 3, long, "const char __user *path, char __user *buf, int bufsiz")
X(chmod, 2, long, "const char __user *filename, umode_t mode")
X(fchmod, 2, long, "unsigned int fd, umode_t mode")
X(chown, 3, long, "const char __user *filename, uid_t user, gid_t group")
X(fchown, 3, long, "unsigned int fd, uid_t user, gid_t group")
X(lchown, 3, long, "const char __user *filename, uid_t user, gid_t group")
X(umask, 1, long, "int mask")
X(gettimeofday, 2, long, "struct timeval __user *tv, struct timezone __user *tz")
X(getrlimit, 2, long, "unsigned int resource, struct rlimit __user *rlim")
X(getrusage, 2, long, "int who, struct rusage __user *ru")
X(sysinfo, 1, long, "struct sysinfo __user *info")
X(times, 1, long, "struct tms __user *tbuf")
X(ptrace, 4, long, "long request, long pid, unsigned long addr, unsigned long data")
X(getuid, 0, long, "")
X(syslog, 3, long, "int type, char __user *buf, int len")
X(getgid, 0, long, "")
X(setuid, 1, long, "uid_t uid")
X(setgid, 1, long, "gid_t gid")
X(geteuid, 0, long, "")
X(getegid, 0, long, "")
X(setpgid, 2, long, "pid_t pid, pid_t pgid")
X(getppid, 0, long, "")
X(getpgrp, 0, long, "")
X(setsid, 0, long, "")
X(setreuid, 2, long, "uid_t ruid, uid_t euid")
X(setregid, 2, long, "gid_t rgid, gid_t egid")
X(getgroups, 2, long, "int gidsetsize, gid_t __user *grouplist")
X(setgroups, 2, long, "int gidsetsize, gid_t __user *grouplist")
X(setresuid, 3, long, "uid_t ruid, uid_t euid, uid_t suid")
X(getresuid, 3, long, "uid_t __user *ruid, uid_t __user *euid, uid_t __user *suid")
X(setresgid, 3, long, "gid_t rgid, gid_t egid, gid_t sgid")
X(getresgid, 3, long, "gid_t __user *rgid, gid_t __user *egid, gid_t __user *sgid")
X(getpgid, 1, long, "pid_t pid")
X(setfsuid, 1, long, "uid_t uid")
X(setfsgid, 1, long, "gid_t gid")
X(getsid, 1, long, "pid_t pid")
X(capget, 2, long, "cap_user_header_t header, cap_user_data_t dataptr")
X(capset, 2, long, "cap_user_header_t header, const cap_user_data_t data")
X(rt_sigpending, 2, long, "sigset_t __user *set, size_t sigsetsize")
X(rt_sigtimedwait, 4, long, "const sigset_t __user *uthese, siginfo_t __user *uinfo, const struct timespec __user *uts, size_t sigsetsize")
X(rt_sigqueueinfo, 3, long, "pid_t pid, int sig, siginfo_t __user *uinfo")
X(rt_sigsuspend, 2, long, "sigset_t __user *unewset, size_t sigsetsize")
X(sigaltstack, 2, long, "const struct sigaltstack __user *uss, struct sigaltstack __user *uoss")
X(utime, 2, long, "char __user *filename, struct utimbuf __user *times")
X(mknod, 3, long, "const char __user *filename, umode_t mode, unsigned dev")
X(uselib, 1, long, "const char __user *library")
X(personality, 1, long, "unsigned int personality")
X(ustat, 2, long, "unsigned dev, struct ustat __user *ubuf")
X(statfs, 2, long, "const char __user * path, struct statfs __user *buf")
X(fstatfs, 2, long, "unsigned int fd, struct statfs __user *buf")
X(sysfs, 3, long, "int option, unsigned long arg1, unsigned long arg2")
X(getpriority, 2, long, "int which, int who")
X(setpriority, 3, long, "int which, int who, int niceval")
X(sched_setparam, 2, long, "pid_t pid, struct sched_param __user *param")
X(sched_getparam, 2, long, "pid_t pid, struct sched_param __user *param")
X(sched_setscheduler, 3, long, "pid_t pid, int policy, struct sched_param __user *param")
X(sched_getscheduler, 1, long, "pid_t pid")
X(sched_get_priority_max, 1, long, "int policy")
X(sched_get_priority_min, 1, long, "int policy")
X(sched_rr_get_interval, 2, long, "pid_t pid, struct timespec __user *interval")
X(mlock, 2, long, "unsigned long start, size_t len")
X(munlock, 2, long, "unsigned long start, size_t len")
X(mlockall, 1, long, "int flags")
X(munlockall, 0, long, "")
X(vhangup, 0, long, "")
X(modify_ldt, 3, int, "int, void __user *, unsigned long")
X(pivot_root, 2, long, "const char __user *new_root, const char __user *put_old")
X(_sysctl, 1, long, "struct __sysctl_args __user *args")
X(prctl, 5, long, "int option, unsigned long arg2, unsigned long arg3, unsigned long arg4, unsigned long arg5")
X(arch_prctl, 2, long, "int, unsigned long")
X(adjtimex, 1, long, "struct timex __user *txc_p")
X(setrlimit, 2, long, "unsigned int resource, struct rlimit __user *rlim")
X(chroot, 1, long, "const char __user *filename")
X(sync, 0, long, "")
X(acct, 1, long, "const char __user *name")
X(settimeofday, 2, long, "struct timeval __user *tv, struct timezone __user *tz")
X(mount, 5, long, "char __user *dev_name, char __user *dir_name, char __user *type, unsigned long flags, void __user *data")
X(umount2, 2, long, "char __user *name, int flags")
X(swapon, 2, long, "const char __user *specialfile, int swap_flags")
X(swapoff, 1, long, "const char __user *specialfile")
X(reboot, 4, long, "int magic1, int magic2, unsigned int cmd, void __user *arg")
X(sethostname, 2, long, "char __user *name, int len")
X(setdomainname, 2, long, "char __user *name, int len")
X(iopl, 1, long, "unsigned int")
X(ioperm, 3, long, "unsigned long from, unsigned long num, int on")
X(create_module, 0, "?", "?")
X(init_module, 3, long, "void __user *umod, unsigned long len, const char __user *uargs")
X(delete_module, 2, long, "const char __user *name_user, unsigned int flags")
X(get_kernel_syms, 0, "?", "?")
X(query_module, 0, "?", "?")
X(quotactl, 4, long, "unsigned int cmd, const char __user *special, qid_t id, void __user *addr")
X(nfsservctl, 0, "?", "?")
X(getpmsg, 0, "?", "?")
X(putpmsg, 0, "?", "?")
X(afs_syscall, 0, "?", "?")
X(tuxcall, 0, "?", "?")
X(security, 0, "?", "?")
X(gettid, 0, long, "")
X(readahead, 3, long, "int fd, loff_t offset, size_t count")
X(setxattr, 5, long, "const char __user *path, const char __user *name, const void __user *value, size_t size, int flags")
X(lsetxattr, 5, long, "const char __user *path, const char __user *name, const void __user *value, size_t size, int flags")
X(fsetxattr, 5, long, "int fd, const char __user *name, const void __user *value, size_t size, int flags")
X(getxattr, 4, long, "const char __user *path, const char __user *name, void __user *value, size_t size")
X(lgetxattr, 4, long, "const char __user *path, const char __user *name, void __user *value, size_t size")
X(fgetxattr, 4, long, "int fd, const char __user *name, void __user *value, size_t size")
X(listxattr, 3, long, "const char __user *path, char __user *list, size_t size")
X(llistxattr, 3, long, "const char __user *path, char __user *list, size_t size")
X(flistxattr, 3, long, "int fd, char __user *list, size_t size")
X(removexattr, 2, long, "const char __user *path, const char __user *name")
X(lremovexattr, 2, long, "const char __user *path, const char __user *name")
X(fremovexattr, 2, long, "int fd, const char __user *name")
X(tkill, 2, long, "pid_t pid, int sig")
X(time, 1, long, "time_t __user *tloc")
X(futex, 6, long, "u32 __user *uaddr, int op, u32 val, struct timespec __user *utime, u32 __user *uaddr2, u32 val3")
X(sched_setaffinity, 3, long, "pid_t pid, unsigned int len, unsigned long __user *user_mask_ptr")
X(sched_getaffinity, 3, long, "pid_t pid, unsigned int len, unsigned long __user *user_mask_ptr")
X(set_thread_area, 1, long, "struct user_desc __user *")
X(io_setup, 2, long, "unsigned nr_reqs, aio_context_t __user *ctx")
X(io_destroy, 1, long, "aio_context_t ctx")
X(io_getevents, 5, long, "aio_context_t ctx_id, long min_nr, long nr, struct io_event __user *events, struct timespec __user *timeout")
X(io_submit, 3, long, "aio_context_t, long, struct iocb __user * __user *")
X(io_cancel, 3, long, "aio_context_t ctx_id, struct iocb __user *iocb, struct io_event __user *result")
X(get_thread_area, 1, long, "struct user_desc __user *")
X(lookup_dcookie, 3, long, "u64 cookie64, char __user *buf, size_t len")
X(epoll_create, 1, long, "int size")
X(epoll_ctl_old, 0, "?", "?")
X(epoll_wait_old, 0, "?", "?")
X(remap_file_pages, 5, long, "unsigned long start, unsigned long size, unsigned long prot, unsigned long pgoff, unsigned long flags")
X(getdents64, 3, long, "unsigned int fd, struct linux_dirent64 __user *dirent, unsigned int count")
X(set_tid_address, 1, long, "int __user *tidptr")
X(restart_syscall, 0, long, "")
X(semtimedop, 4, long, "int semid, struct sembuf __user *sops, unsigned nsops, const struct timespec __user *timeout")
X(fadvise64, 4, long, "int fd, loff_t offset, size_t len, int advice")
X(timer_create, 3, long, "clockid_t which_clock, struct sigevent __user *timer_event_spec, timer_t __user * created_timer_id")
X(timer_settime, 4, long, "timer_t timer_id, int flags, const struct itimerspec __user *new_setting, struct itimerspec __user *old_setting")
X(timer_gettime, 2, long, "timer_t timer_id, struct itimerspec __user *setting")
X(timer_getoverrun, 1, long, "timer_t timer_id")
X(timer_delete, 1, long, "timer_t timer_id")
X(clock_settime, 2, long, "clockid_t which_clock, const struct timespec __user *tp")
X(clock_gettime, 2, long, "clockid_t which_clock, struct timespec __user *tp")
X(clock_getres, 2, long, "clockid_t which_clock, struct timespec __user *tp")
X(clock_nanosleep, 4, long, "clockid_t which_clock, int flags, const struct timespec __user *rqtp, struct timespec __user *rmtp")
X(exit_group, 1, long, "int error_code")
X(epoll_wait, 4, long, "int epfd, struct epoll_event __user *events, int maxevents, int timeout")
X(epoll_ctl, 4, long, "int epfd, int op, int fd, struct epoll_event __user *event")
X(tgkill, 3, long, "pid_t tgid, pid_t pid, int sig")
X(utimes, 2, long, "char __user *filename, struct timeval __user *utimes")
X(vserver, 0, "?", "?")
X(mbind, 6, long, "unsigned long start, unsigned long len, unsigned long mode, const unsigned long __user *nmask, unsigned long maxnode, unsigned flags")
X(set_mempolicy, 3, long, "int mode, const unsigned long __user *nmask, unsigned long maxnode")
X(get_mempolicy, 5, long, "int __user *policy, unsigned long __user *nmask, unsigned long maxnode, unsigned long addr, unsigned long flags")
X(mq_open, 4, long, "const char __user *name, int oflag, umode_t mode, struct mq_attr __user *attr")
X(mq_unlink, 1, long, "const char __user *name")
X(mq_timedsend, 5, long, "mqd_t mqdes, const char __user *msg_ptr, size_t msg_len, unsigned int msg_prio, const struct timespec __user *abs_timeout")
X(mq_timedreceive, 5, long, "mqd_t mqdes, char __user *msg_ptr, size_t msg_len, unsigned int __user *msg_prio, const struct timespec __user *abs_timeout")
X(mq_notify, 2, long, "mqd_t mqdes, const struct sigevent __user *notification")
X(mq_getsetattr, 3, long, "mqd_t mqdes, const struct mq_attr __user *mqstat, struct mq_attr __user *omqstat")
X(kexec_load, 4, long, "unsigned long entry, unsigned long nr_segments, struct kexec_segment __user *segments, unsigned long flags")
X(waitid, 5, long, "int which, pid_t pid, struct siginfo __user *infop, int options, struct rusage __user *ru")
X(add_key, 5, long, "const char __user *_type, const char __user *_description, const void __user *_payload, size_t plen, key_serial_t destringid")
X(request_key, 4, long, "const char __user *_type, const char __user *_description, const char __user *_callout_info, key_serial_t destringid")
X(keyctl, 5, long, "int cmd, unsigned long arg2, unsigned long arg3, unsigned long arg4, unsigned long arg5")
X(ioprio_set, 3, long, "int which, int who, int ioprio")
X(ioprio_get, 2, long, "int which, int who")
X(inotify_init, 0, long, "")
X(inotify_add_watch, 3, long, "int fd, const char __user *path, u32 mask")
X(inotify_rm_watch, 2, long, "int fd, __s32 wd")
X(migrate_pages, 4, long, "pid_t pid, unsigned long maxnode, const unsigned long __user *from, const unsigned long __user *to")
X(openat, 4, long, "int dfd, const char __user *filename, int flags, umode_t mode")
X(mkdirat, 3, long, "int dfd, const char __user * pathname, umode_t mode")
X(mknodat, 4, long, "int dfd, const char __user * filename, umode_t mode, unsigned dev")
X(fchownat, 5, long, "int dfd, const char __user *filename, uid_t user, gid_t group, int flag")
X(futimesat, 3, long, "int dfd, const char __user *filename, struct timeval __user *utimes")
X(newfstatat, 4, long, "int dfd, const char __user *filename, struct stat __user *statbuf, int flag")
X(unlinkat, 3, long, "int dfd, const char __user * pathname, int flag")
X(renameat, 4, long, "int olddfd, const char __user * oldname, int newdfd, const char __user * newname")
X(linkat, 5, long, "int olddfd, const char __user *oldname, int newdfd, const char __user *newname, int flags")
X(symlinkat, 3, long, "const char __user * oldname, int newdfd, const char __user * newname")
X(readlinkat, 4, long, "int dfd, const char __user *path, char __user *buf, int bufsiz")
X(fchmodat, 3, long, "int dfd, const char __user * filename, umode_t mode")
X(faccessat, 3, long, "int dfd, const char __user *filename, int mode")
X(pselect6, 6, long, "int, fd_set __user *, fd_set __user *, fd_set __user *, struct timespec __user *, void __user *")
X(ppoll, 5, long, "struct pollfd __user *, unsigned int, struct timespec __user *, const sigset_t __user *, size_t")
X(unshare, 1, long, "unsigned long unshare_flags")
X(set_robust_list, 2, long, "struct robust_list_head __user *head, size_t len")
X(get_robust_list, 3, long, "int pid, struct robust_list_head __user * __user *head_ptr, size_t __user *len_ptr")
X(splice, 6, long, "int fd_in, loff_t __user *off_in, int fd_out, loff_t __user *off_out, size_t len, unsigned int flags")
X(tee, 4, long, "int fdin, int fdout, size_t len, unsigned int flags")
X(sync_file_range, 4, long, "int fd, loff_t offset, loff_t nbytes, unsigned int flags")
X(vmsplice, 4, long, "int fd, const struct iovec __user *iov, unsigned long nr_segs, unsigned int flags")
X(move_pages, 6, long, "pid_t pid, unsigned long nr_pages, const void __user * __user *pages, const int __user *nodes, int __user *status, int flags")
X(utimensat, 4, long, "int dfd, const char __user *filename, struct timespec __user *utimes, int flags")
X(epoll_pwait, 6, long, "int epfd, struct epoll_event __user *events, int maxevents, int timeout, const sigset_t __user *sigmask, size_t sigsetsize")
X(signalfd, 3, long, "int ufd, sigset_t __user *user_mask, size_t sizemask")
X(timerfd_create, 2, long, "int clockid, int flags")
X(eventfd, 1, long, "unsigned int count")
X(fallocate, 4, long, "int fd, int mode, loff_t offset, loff_t len")
X(timerfd_settime, 4, long, "int ufd, int flags, const struct itimerspec __user *utmr, struct itimerspec __user *otmr")
X(timerfd_gettime, 2, long, "int ufd, struct itimerspec __user *otmr")
X(accept4, 4, long, "int, struct sockaddr __user *, int __user *, int")
X(signalfd4, 4, long, "int ufd, sigset_t __user *user_mask, size_t sizemask, int flags")
X(eventfd2, 2, long, "unsigned int count, int flags")
X(epoll_create1, 1, long, "int flags")
X(dup3, 3, long, "unsigned int oldfd, unsigned int newfd, int flags")
X(pipe2, 2, long, "int __user *fildes, int flags")
X(inotify_init1, 1, long, "int flags")
X(preadv, 5, long, "unsigned long fd, const struct iovec __user *vec, unsigned long vlen, unsigned long pos_l, unsigned long pos_h")
X(pwritev, 5, long, "unsigned long fd, const struct iovec __user *vec, unsigned long vlen, unsigned long pos_l, unsigned long pos_h")
X(rt_tgsigqueueinfo, 4, long, "pid_t tgid, pid_t pid, int sig, siginfo_t __user *uinfo")
X(perf_event_open, 5, long, "struct perf_event_attr __user *attr_uptr, pid_t pid, int cpu, int group_fd, unsigned long flags")
X(recvmmsg, 5, long, "int fd, struct mmsghdr __user *msg, unsigned int vlen, unsigned flags, struct timespec __user *timeout")
X(fanotify_init, 2, long, "unsigned int flags, unsigned int event_f_flags")
X(fanotify_mark, 5, long, "int fanotify_fd, unsigned int flags, u64 mask, int fd, const char __user *pathname")
X(prlimit64, 4, long, "pid_t pid, unsigned int resource, const struct rlimit64 __user *new_rlim, struct rlimit64 __user *old_rlim")
X(name_to_handle_at, 5, long, "int dfd, const char __user *name, struct file_handle __user *handle, int __user *mnt_id, int flag")
X(open_by_handle_at, 3, long, "int mountdirfd, struct file_handle __user *handle, int flags")
X(clock_adjtime, 2, long, "clockid_t which_clock, struct timex __user *tx")
X(syncfs, 1, long, "int fd")
X(sendmmsg, 4, long, "int fd, struct mmsghdr __user *msg, unsigned int vlen, unsigned flags")
X(setns, 2, long, "int fd, int nstype")
X(getcpu, 3, long, "unsigned __user *cpu, unsigned __user *node, struct getcpu_cache __user *cache")
X(process_vm_readv, 6, long, "pid_t pid, const struct iovec __user *lvec, unsigned long liovcnt, const struct iovec __user *rvec, unsigned long riovcnt, unsigned long flags")
X(process_vm_writev, 6, long, "pid_t pid, const struct iovec __user *lvec, unsigned long liovcnt, const struct iovec __user *rvec, unsigned long riovcnt, unsigned long flags")
X(kcmp, 5, long, "pid_t pid1, pid_t pid2, int type, unsigned long idx1, unsigned long idx2")
X(finit_module, 3, long, "int fd, const char __user *uargs, int flags")
X(sched_setattr, 3, long, "pid_t pid, struct sched_attr __user *attr, unsigned int flags")
X(sched_getattr, 4, long, "pid_t pid, struct sched_attr __user *attr, unsigned int size, unsigned int flags")
X(renameat2, 5, long, "int olddfd, const char __user *oldname, int newdfd, const char __user *newname, unsigned int flags")
X(seccomp, 3, long, "unsigned int op, unsigned int flags, const char __user *uargs")
X(getrandom, 3, long, "char __user *buf, size_t count, unsigned int flags")
X(memfd_create, 2, long, "const char __user *uname_ptr, unsigned int flags")
X(kexec_file_load, 5, long, "int kernel_fd, int initrd_fd, unsigned long cmdline_len, const char __user *cmdline_ptr, unsigned long flags")
X(bpf, 3, long, "int cmd, union bpf_attr *attr, unsigned int size")
X(execveat, 5, long, "int dfd, const char __user *filename, const char __user *const __user *argv, const char __user *const __user *envp, int flags")
X(userfaultfd, 1, long, "int flags")
X(membarrier, 2, long, "int cmd, int flags")
X(mlock2, 3, long, "unsigned long start, size_t len, int flags")
X(copy_file_range, 6, long, "int fd_in, loff_t __user *off_in, int fd_out, loff_t __user *off_out, size_t len, unsigned int flags")
X(preadv2, 6, long, "unsigned long fd, const struct iovec __user *vec, unsigned long vlen, unsigned long pos_l, unsigned long pos_h, int flags")
X(pwritev2, 6, long, "unsigned long fd, const struct iovec __user *vec, unsigned long vlen, unsigned long pos_l, unsigned long pos_h, int flags")
X(pkey_mprotect, 4, long, "unsigned long start, size_t len, unsigned long prot, int pkey")
X(pkey_alloc, 2, long, "unsigned long flags, unsigned long init_val")
X(pkey_free, 1, long, "int pkey")
